# Generated by Django 3.1.5 on 2021-01-08 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gorod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование города')),
            ],
            options={
                'verbose_name': 'Города',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='Operahii',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название операции')),
            ],
            options={
                'verbose_name': 'Операции',
                'verbose_name_plural': 'Операции',
            },
        ),
        migrations.CreateModel(
            name='Polzovateli',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('familia', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('otchestvo', models.CharField(max_length=50, verbose_name='Отчество')),
                ('passport', models.CharField(max_length=255, verbose_name='Паспорт')),
                ('nomer_telefona', models.IntegerField(max_length=11, verbose_name='Номер телефона')),
                ('login', models.CharField(max_length=50, verbose_name='Логин')),
                ('password', models.CharField(max_length=255, verbose_name='Пароль')),
            ],
            options={
                'verbose_name': 'Пользователи',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Predlozheniya',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(max_length=50, verbose_name='Тип объекта')),
                ('adres', models.CharField(max_length=255, verbose_name='Адрес')),
                ('kolvo_etashei', models.IntegerField(max_length=3, verbose_name='Кол-во этажей')),
                ('etash', models.IntegerField(max_length=3, verbose_name='Этаж')),
                ('kolvo_komnat', models.IntegerField(max_length=2, verbose_name='Кол-во комнат')),
                ('plozhad', models.IntegerField(max_length=4, verbose_name='Площадь')),
                ('xoz_postroyki', models.CharField(max_length=50, verbose_name='Хоз. постройки')),
                ('opisanie', models.CharField(max_length=255, verbose_name='Описание')),
                ('stoimost', models.IntegerField(max_length=15, verbose_name='Стоимость')),
                ('actualnost', models.BooleanField(verbose_name='Актуальность')),
                ('id_goroda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectApp.gorod', verbose_name='ID Города')),
                ('id_prodavca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectApp.polzovateli', verbose_name='ID Продавца')),
            ],
            options={
                'verbose_name': 'Предложения',
                'verbose_name_plural': 'Предложения',
            },
        ),
        migrations.CreateModel(
            name='Rayoni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование района')),
            ],
            options={
                'verbose_name': 'Районы',
                'verbose_name_plural': 'Районы',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование роли')),
            ],
            options={
                'verbose_name': 'Роли',
                'verbose_name_plural': 'Роли',
            },
        ),
        migrations.CreateModel(
            name='Tariphy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('stavka_polgoda', models.IntegerField(max_length=3, verbose_name='Процентная ставка за полгода')),
                ('stavka_god', models.IntegerField(max_length=3, verbose_name='Процентная ставка за 1 год')),
                ('stavka_tri', models.IntegerField(max_length=3, verbose_name='Процентная ставка за 3 год')),
            ],
            options={
                'verbose_name': 'Тарифы',
                'verbose_name_plural': 'Тарифы',
            },
        ),
        migrations.CreateModel(
            name='Straxovoi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kolvo_let', models.IntegerField(max_length=4, verbose_name='Кол-во лет')),
                ('id_predlozhenia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectApp.predlozheniya', verbose_name='ID Предложения')),
                ('id_rieltora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectApp.polzovateli', verbose_name='ID Риэлтора')),
                ('id_tarifa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectApp.tariphy', verbose_name='ID Тарифа')),
            ],
            options={
                'verbose_name': 'Страховой контракт',
                'verbose_name_plural': 'Страховой контракт',
            },
        ),
        migrations.CreateModel(
            name='Spros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(max_length=50, verbose_name='Тип объекта')),
                ('kolvo_etashei_ot', models.IntegerField(max_length=3, verbose_name='Кол-во этажей от')),
                ('kolvo_etashei_do', models.IntegerField(max_length=3, verbose_name='Кол-во этажей до')),
                ('etash_ot', models.IntegerField(max_length=3, verbose_name='Этаж от')),
                ('etash_do', models.IntegerField(max_length=3, verbose_name='Этаж до')),
                ('kolvo_komnat_ot', models.IntegerField(max_length=2, verbose_name='Кол-во комнат от')),
                ('kolvo_komnat_do', models.IntegerField(max_length=2, verbose_name='Кол-во комнат до')),
                ('ploshad_ot', models.IntegerField(max_length=4, verbose_name='Площадь от')),
                ('ploshad_do', models.IntegerField(max_length=4, verbose_name='Площадь до')),
                ('stoimost_ot', models.IntegerField(max_length=15, verbose_name='Стоимость от')),
                ('stoimost_do', models.IntegerField(max_length=15, verbose_name='Стоимость до')),
                ('actualnost', models.BooleanField(verbose_name='Актуальность')),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectApp.polzovateli', verbose_name='ID Клиента')),
                ('id_goroda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectApp.gorod', verbose_name='ID Города')),
                ('id_rayona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectApp.rayoni', verbose_name='ID Района')),
            ],
            options={
                'verbose_name': 'Спрос',
                'verbose_name_plural': 'Спрос',
            },
        ),
        migrations.CreateModel(
            name='Sdelki',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата сделки')),
                ('komissionie_agenty', models.IntegerField(max_length=4, verbose_name='Комиссионные агенты')),
                ('proc_rieltora', models.IntegerField(max_length=3, verbose_name='Процент риэлтора')),
                ('id_kontrakta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectApp.straxovoi', verbose_name='ID Контракта')),
                ('id_operachii', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectApp.operahii', verbose_name='Код операции')),
                ('id_pokypatelia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectApp.polzovateli', verbose_name='ID Покупателя')),
            ],
            options={
                'verbose_name': 'Сделки',
                'verbose_name_plural': 'Сделки',
            },
        ),
        migrations.AddField(
            model_name='predlozheniya',
            name='id_rayona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectApp.rayoni', verbose_name='ID Района'),
        ),
        migrations.AddField(
            model_name='polzovateli',
            name='id_role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectApp.role', verbose_name='ID Роли'),
        ),
    ]
