# Generated by Django 3.1.5 on 2021-01-10 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gorod',
            options={'ordering': ('id', 'name'), 'verbose_name': 'Города', 'verbose_name_plural': 'Города'},
        ),
        migrations.AlterModelOptions(
            name='operahii',
            options={'ordering': ('id', 'name'), 'verbose_name': 'Операции', 'verbose_name_plural': 'Операции'},
        ),
        migrations.AlterModelOptions(
            name='polzovateli',
            options={'ordering': ('familia', 'name', 'otchestvo', 'passport', 'nomer_telefona', 'login', 'password', 'id_role'), 'verbose_name': 'Пользователи', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterModelOptions(
            name='predlozheniya',
            options={'ordering': ('object_type', 'id_rayona', 'id_goroda', 'adres', 'kolvo_etashei', 'etash', 'kolvo_komnat', 'plozhad', 'xoz_postroyki', 'opisanie', 'stoimost', 'id_prodavca', 'actualnost'), 'verbose_name': 'Предложения', 'verbose_name_plural': 'Предложения'},
        ),
        migrations.AlterModelOptions(
            name='rayoni',
            options={'ordering': ('id', 'name'), 'verbose_name': 'Районы', 'verbose_name_plural': 'Районы'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ('id', 'name'), 'verbose_name': 'Роли', 'verbose_name_plural': 'Роли'},
        ),
        migrations.AlterModelOptions(
            name='sdelki',
            options={'ordering': ('id_kontrakta', 'id_pokypatelia', 'date', 'komissionie_agenty', 'proc_rieltora', 'id_operachii'), 'verbose_name': 'Сделки', 'verbose_name_plural': 'Сделки'},
        ),
        migrations.AlterModelOptions(
            name='spros',
            options={'ordering': ('object_type', 'id_rayona', 'id_goroda', 'kolvo_etashei_ot', 'kolvo_etashei_do', 'etash_ot', 'etash_do', 'kolvo_komnat_ot', 'kolvo_komnat_do', 'ploshad_ot', 'ploshad_do', 'stoimost_ot', 'stoimost_do', 'id_client', 'actualnost'), 'verbose_name': 'Спрос', 'verbose_name_plural': 'Спрос'},
        ),
        migrations.AlterModelOptions(
            name='straxovoi',
            options={'ordering': ('id_predlozhenia', 'id_rieltora', 'id_tarifa', 'kolvo_let'), 'verbose_name': 'Страховой контракт', 'verbose_name_plural': 'Страховой контракт'},
        ),
        migrations.AlterModelOptions(
            name='tariphy',
            options={'ordering': ('name', 'stavka_polgoda', 'stavka_god', 'stavka_tri'), 'verbose_name': 'Тарифы', 'verbose_name_plural': 'Тарифы'},
        ),
        migrations.AlterField(
            model_name='gorod',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='operahii',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='polzovateli',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='predlozheniya',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rayoni',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='role',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sdelki',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='spros',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='straxovoi',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tariphy',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
